version: "3"
services :
  user_service:
    container_name: users
    restart: always
    build: USERS
    image: users:latest
    ports:
      - "80:8080"
    links:
      - user_mongodb
  user_mongodb:
    image: "mongo"
    ports:
     - "27005:27017"
